NDefines.NDiplomacy.VASSALIZE_BASE_DEVELOPMENT_CAP = 250 --100
NDefines.NDiplomacy.TRUCE_YEARS = 3 --5
NDefines.NDiplomacy.SCALED_TRUCE_YEARS = 2  --10
NDefines.NDiplomacy.REQUEST_HEIR_AE = 20    --20
NDefines.NDiplomacy.SPY_NETWORK_AE_EFFECT = -0.15    -- -0.3
NDefines.NDiplomacy.FABRICATE_CLAIM_COST_MODIFIER_PER_CLAIM = 0.1    --0.25
NDefines.NDiplomacy.PO_FORM_PU_AE = 0.16   --0.20
NDefines.NDiplomacy.PO_DEMAND_PROVINCES_AE = 0.8  --0.6
NDefines.NDiplomacy.PO_BECOME_VASSAL_AE = 0.5   --0.5
NDefines.NDiplomacy.PO_TRANSFER_VASSAL_AE = 0.3   --0.3
NDefines.NDiplomacy.AE_HRE_INTERNAL = 1  --0.5
NDefines.NDiplomacy.AE_DISTANCE_BASE = 0.4 --0.75
NDefines.NDiplomacy.AE_INFIDEL_CONQUEST = 1  --0.25
NDefines.NDiplomacy.WAR_REPARATIONS_FACTOR = 0.16  --0.1
NDefines.NDiplomacy.WAR_REPARATIONS_YEARS = 6   --10
NDefines.NDiplomacy.AE_PROVINCE_CAP = 60  --30
--NDefines.NDiplomacy.PEACE_COST_JOIN_HRE = 1000 --90
NDefines.NDiplomacy.MAX_PEACE_TREATY_AE = 200  --50
NDefines.NDiplomacy.PEACE_COST_DEMAND_PROVINCE = 0.45   --0.8
NDefines.NDiplomacy.PEACE_COST_CONVERSION = 0.3  --0.8
NDefines.NDiplomacy.PEACE_COST_CONCEDE_PROVINCE = 0.45   --0.8
NDefines.NDiplomacy.PEACE_COST_BECOME_VASSAL = 0.3    --0.8
NDefines.NDiplomacy.PEACE_COST_RETURN_CORE = 0.25    --0.8
NDefines.NDiplomacy.PEACE_COST_RELEASE_ANNEXED = 0.5   --0.8
NDefines.NDiplomacy.PEACE_COST_RELEASE_VASSAL = 0.2 --0.4
NDefines.NDiplomacy.PEACE_COST_DEMAND_NON_OCCUPIED_PROVINCE_MULT = 2.5  --1.1
NDefines.NDiplomacy.AUTONOMY_WARSCORE_COST_MODIFIER = 0.9 --0.33
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_STATE_WITH_PROSPERITY = 0.04 --0.04
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_TRIBUTARY_DEV = 0.18  --0.15
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_DEVASTATION = -5   -- -10
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_5_LOANS = -0.3
NDefines.NDiplomacy.AE_COALITION_THRESHOLD = -50 -- -50
--NDefines.NDiplomacy.AUTODIPLO_TARGET_COALITION_START_TO_IGNORE_AE_ABOVE_THIS = -10  -- -25
NDefines.NDiplomacy.TRIBUTE_BASE_ADM = 0.03
NDefines.NDiplomacy.TRIBUTE_BASE_DIP = 0.03
NDefines.NDiplomacy.TRIBUTE_BASE_MIL = 0.03
NDefines.NDiplomacy.TRIBUTE_MAX_MONARCH_POWER = 30 --12
NDefines.NDiplomacy.ALLY_PEACE_COST_MULT = 2  --2
NDefines.NDiplomacy.ALLY_AE_MULT = 3  --1.5
NDefines.NEconomy.ADVISOR_COST = 1.25 --1.0
NDefines.NEconomy.BANKRUPTCY_PROVINCE_DEVASTATION_GAIN = 5 --10
NDefines.NCountry.MAXIMUM_ADVISOR_SKILL = 15 --5
NDefines.NCountry.ADVISOR_COST_INCREASE_PER_YEAR = 0.005
NDefines.NCountry.CORE_LOSE = 75  --50
NDefines.NCountry.CORE_LOSE_CULTURE_GROUP = 800    --150
NDefines.NCountry.OVEREXTENSION_FACTOR = 0.33    --0.8
NDefines.NCountry.OVEREXTENSION_OVERSEAS_FACTOR = 0.25  --0.5
NDefines.NCountry.MONTHS_TO_CORE = 48  --36
NDefines.NDiplomacy.MARCH_BASE_DEVELOPMENT_CAP = 2000 --200
NDefines.NDiplomacy.JOIN_HRE_DEVELOPMENT_CAP_VASSAL = 5000  --200
NDefines.NCountry.POWER_MAX = 2499 --999
NDefines.NCountry.RAZE_PROVINCE_COOLDOWN_YRS = 0  --20
NDefines.NCountry.COUNTRY_DEVELOPMENT_SCALE = 4000  --600
NDefines.NCountry.OVERSEAS_CLIENT_STATES = 1  --0

NDefines.NMilitary.DEFAULT_WARGOAL_BATTLESCORE_BONUS = 8 --3
NDefines.NMilitary.ASSAULT_WIDTH_LIMIT = 10 --5
NDefines.NMilitary.MORALE_RECOVERY_SPEED = 0.12  --0.15
NDefines.NMilitary.MORALE_RECOVERY_SPEED_OWN_TERRITORY = 0.1 --0.05
NDefines.NMilitary.HOSTILE_TERRITORY_SPEED_MODIFIER = -0.15  -- 0
NDefines.NMilitary.LOOTED_SCALE = 2  --1
NDefines.NMilitary.LOOTED_MAX = 20 --5
NDefines.NMilitary.INF_LOOT = 0.3  --0.1
NDefines.NMilitary.CAV_LOOT = 0.8  --0.3
NDefines.NMilitary.ART_LOOT = 0.1  --0.05

NDefines.NCountry.HORDE_RAZE_TECH_BASE_LEVEL = 10   --3

--NDefines.NAI.ACCEPTABLE_BALANCE_DEFAULT = 1.05  --1.2
NDefines.NAI.IMPORANT_PROVINCE_THRESHOLD = 0.02 --0.05
NDefines.NAI.ACCEPTABLE_BALANCE_MULT_FRIEND_IN_COMBAT = 0.7  --0.8
NDefines.NAI.ACCEPTABLE_BALANCE_MULT_OFFENSIVE = 0.9  --0.85
NDefines.NAI.DEVELOPMENT_CAP_BASE = 30
NDefines.NAI.DEVELOPMENT_CAP_MULT = 10
--NDefines.NAI.EDICT_VALUE_THRESHOLD = 60 --120
--NDefines.NAI.AGGRESSIVENESS = 400  -200
--NDefines.NAI.AGGRESSIVENESS_BONUS_EASY_WAR = 1000  --300
NDefines.NAI.ARTILLERY_FRACTION = 0.25  --0.35
NDefines.NAI.FORCE_COMPOSITION_CHANGE_TECH_LEVEL = 16  --11
NDefines.NAI.PROMOTE_ADVISOR_BASE_AI_DESIRE = 30   --10
NDefines.NAI.AI_FORT_PER_DEV_RATIO = 50  --75
NDefines.NAI.FORT_BUDGET_FRACTION = 0.5  --0.3
NDefines.NAI.PEACE_COALITION_FACTOR = 5 --30
NDefines.NAI.PEACE_REBELS_FACTOR = 40  --20
NDefines.NAI.DIPLOMATIC_ACTION_OFFER_CONDOTTIERI_ONLY_MILITARY_RULERS = 0 --1
NDefines.NAI.DIPLOMATIC_ACTION_OFFER_CONDOTTIERI_ONLY_NEIGHBORS = 0 --1
NDefines.NAI.ADVISOR_BUDGET_FRACTION_MAX = 0.7 --0.35
NDefines.NAI.ADVISOR_BUDGET_FRACTION_MIN = 0.15 --0.15
NDefines.NAI.ADVISOR_BUDGET_FRACTION_MERITOCRACY_MAX = 0.8 --0.5
NDefines.NAI.ADVISOR_BUDGET_FRACTION_MERITOCRACY_MIN = 0.26 --0.25

NDefines.NCountry.EXPLOIT_COOLDOWN_MONTHS = 6  --240


NDefines.NCountry.MIN_LIBERTY_DESIRE_INFLUENCE = -75  -- -100
NDefines.NCountry.LIBERTY_DESIRE_TRUST = -0.6  -- -0.4
NDefines.NCountry.LIBERTY_DESIRE_RELATIVE_POWER = 100  --75

NDefines.NAI.CORRUPTION_BUDGET_FRACTION = 0.75  --0.25
NDefines.NAI.FORT_NEXT_TO_FORT_MULT = 0.25  --0.75

NDefines.NCountry.STATE_MAINTENANCE_CULTURE_FACTOR = 0.25   --0.25
NDefines.NCountry.STATE_MAINTENANCE_DEV_FACTOR = 0.02  --0.007
NDefines.NCountry.STATE_MAINTENANCE_DISTANCE_FACTOR = 0.006  --0.001
NDefines.NEconomy.EDICTS_COST_INCREASE = 0.25  --2
NDefines.NEconomy.AUTONOMY_AT_CONQUEST_CORE = 20 --0



NDefines.NGame.GREAT_POWER_FRENZY_START = "1640.1.1"   --"1700.1.1"
NDefines.NGame.GREAT_POWER_FRENZY_QUICKSTART = 0  --0

NDefines.NAI.FIRE_ADVISOR_LOAN_REQUIREMENT = 50   --5

NDefines.NDiplomacy.SUPPORT_REBELS_DURATION = 0 --5

NDefines.NMilitary.CONTROL_DEVASTATION_IMPACT = -2  -- -1

NDefines.NCountry.PS_ADVANCE_TECH = 800 --600
--NDefines.NCountry.TECH_AHEAD_OF_TIME = 0.075 --0.1
NDefines.NCountry.TECH_TIME_COST = 1.5  --0.3
NDefines.NCountry.NEIGHBOURBONUS = -0.15  --  -0.05
NDefines.NCountry.NEIGHBOURBONUS_CAP = -1  --   -0.75


NDefines.NCountry.CORRUPTION_COST = 0.075 --0.05
NDefines.NAI.ADVISOR_PROMOTION_AGE_CUTOFF = 50  --40
NDefines.NAI.EDICT_VALUE_THRESHOLD = 5
NDefines.NAI.EDICT_VALUE_THRESHOLD_MULTIPLY_DEFICIT = 3
NDefines.NAI.EDICT_VALUE_THRESHOLD_MULTIPLY_LOW_INCOME = 1
NDefines.NAI.STATE_MAINTENANCE_BUDGET_FRACTION = 0.8
NDefines.NAIEconomy.STATE_MAINTENANCE_FRACTION = 0.8
NDefines.NAI.FORT_CAPITAL_DESIRE = 100
NDefines.NAIEconomy.BUDGETING_ADJUSTMENT_STEP = 0.11
NDefines.NAIEconomy.MILITARY_FOCUS_DEFAULT = 2.0
NDefines.NAIEconomy.MILITARY_FOCUS_LOWER_BOUND = 2.0
NDefines.NAIEconomy.MILITARY_FOCUS_UPPER_BOUND = 3.5
NDefines.NAI.NOMINAL_ARMY_SIZE_MULTIPLIER = 1.25
NDefines.NAIEconomy.ARMY_FRACTION_PEACEFUL = 1.5  --2.1
NDefines.NAIEconomy.ARMY_FRACTION_MILITARIST = 1.7  --2.5
NDefines.NAIEconomy.ARMY_FRACTION_MILITARIZE = 2.2
NDefines.NAI.MAX_BUILDING_COST_INCOME_MONTHS = 30
NDefines.NAI.MAX_SAVINGS = 40
NDefines.NAI.DESIRED_DEFICIT = 0.2
NDefines.NAI.DESIRED_SURPLUS = 0.3
NDefines.NAI.ONLY_INFANTRY_MERCS = 0
NDefines.NAI.PEACE_TERMS_RETURN_CORES_VASSAL_MULT = 5  --2
NDefines.NAI.PEACE_TERMS_REVOKE_CORES_BASE_MULT = 0 --1
NDefines.NAI.PEACE_TERMS_RELEASE_VASSAL_SAME_CULTURE_MULT = 0.35  --0.65
NDefines.NAI.PEACE_TERMS_RELEASE_VASSAL_SAME_CULTURE_GROUP_MULT = 0.5  --0.75
NDefines.NAI.PEACE_TERMS_RELEASE_ANNEXED_MAX_MULT = 0.6  --1.3
NDefines.NAI.PEACE_TERMS_RELEASE_ANNEXED_SAME_CULTURE_MULT = 0.1  --0.65
NDefines.NAI.PEACE_TERMS_RELEASE_ANNEXED_SAME_CULTURE_GROUP_MULT = 0.2   --0.75
NDefines.NAI.PEACE_TERMS_RELEASE_ANNEXED_HRE_MULT = 10  --2
NDefines.NAI.PEACE_TERMS_WAR_REPARATIONS_BASE_MULT = 2  --0.1
NDefines.NAI.PEACE_TERMS_WAR_REPARATIONS_MIN_INCOME_RATIO = 0.01  --0.5
NDefines.NAI.PEACE_TERMS_GOLD_BASE_MULT = 1  --0.1
NDefines.NAI.GOVERNING_CAPACITY_OVER_PERCENTAGE_TOLERATED = 0.3  --0.5
NDefines.NAI.PEACE_TERMS_PROVINCE_CLAIM_MULT = 6  --2
NDefines.NAI.PEACE_TERMS_PROVINCE_CORE_MULT = 10  --3

NDefines.NAI.PEACE_TERMS_RELEASE_ANNEXED_BASE_MULT = 0.75  --0.75
NDefines.NAI.PEACE_TERMS_RELEASE_ANNEXED_MAX_MULT = 2 --1.3


NDefines.NAIEconomy.LOAN_REPAYMENT_SAVINGS_PRIORITY = 1000
NDefines.NAIEconomy.LOAN_REPAYMENT_SAVINGS_PRIORITY_WARTIME = 0
	
NDefines.NMilitary.MONTHLY_REINFORCE = 0.05  --0.1
NDefines.NMilitary.EXTRA_LAND_REINFORCE_COST = 0.75  --2
NDefines.NEconomy.LAND_TECH_MAINTENANCE_IMPACT = 0.04 --0.02
NDefines.NEconomy.NAVAL_TECH_MAINTENANCE_IMPACT = 0.03 -- 0.02
NDefines.NEconomy.LAND_TECH_MERC_MAINTENANCE_IMPACT = 0.12 --0.08
	
NDefines.NCountry.EXPAND_INFRASTRUCTURE_DEV_LIMIT = 15  --15

NDefines.NCountry.EMBRACE_INSTITUTION_COST = 25  --2.5
NDefines.NCountry.INSTITUTION_BONUS_FROM_IMP_DEVELOPMENT = 4  --5
NDefines.NCountry.INSTITUTION_CAP_IMP_DEVELOPMENT = 8  --10
NDefines.NCountry.INSTITUTION_BASE_IMP_DEVELOPMENT = 30
NDefines.NCountry.PS_IMPROVE_PROVINCE_BASE = 150 --50
NDefines.NCountry.ENFORCE_CULTURE_TAX_MULTIPLIER = 0 --2

NDefines.NNationDesigner.POINTS_AVAILABLE = 800

NDefines.NDiplomacy.PO_SPREAD_REVOLUTION_MAX_POWER_GAIN = 9999 ---999

