--杂项
NDefines.NDiplomacy.VASSALIZE_BASE_DEVELOPMENT_CAP = 250 --100
NDefines.NDiplomacy.TRUCE_YEARS = 3 --5
NDefines.NDiplomacy.SCALED_TRUCE_YEARS = 5  --10
NDefines.NDiplomacy.MARCH_BASE_DEVELOPMENT_CAP = 2000 --200
NDefines.NDiplomacy.JOIN_HRE_DEVELOPMENT_CAP_VASSAL = 5000  --200
NDefines.NDiplomacy.SUPPORT_REBELS_DURATION = 1 --5
NDefines.NDiplomacy.PO_SPREAD_REVOLUTION_MAX_POWER_GAIN = 9999 ---999

--AE
NDefines.NDiplomacy.REQUEST_HEIR_AE = 15    --20
NDefines.NDiplomacy.SPY_NETWORK_AE_EFFECT = -0.2    -- -0.3
NDefines.NDiplomacy.SPY_NETWORK_TECH_EFFECT = -0.1 --0.05
NDefines.NDiplomacy.SPY_NETWORK_TECH_EFFECT_MAX = -0.5 --0.3
NDefines.NDiplomacy.FABRICATE_CLAIM_COST_MODIFIER_PER_CLAIM = 0.1    --0.25
NDefines.NDiplomacy.PO_FORM_PU_AE = 0.1   --0.20
NDefines.NDiplomacy.AE_SAME_RELIGION = 0.75  --0.5
NDefines.NDiplomacy.PO_DEMAND_PROVINCES_AE = 0.6 --0.6
NDefines.NDiplomacy.PO_BECOME_VASSAL_AE = 0.5   --0.5
NDefines.NDiplomacy.PO_TRANSFER_VASSAL_AE = 0.2   --0.3
NDefines.NDiplomacy.AE_HRE_INTERNAL = 1  --0.5
NDefines.NDiplomacy.AE_DISTANCE_BASE = 0.85 --0.75
NDefines.NDiplomacy.AE_INFIDEL_CONQUEST = 0.5  --0.25
NDefines.NDiplomacy.WAR_REPARATIONS_FACTOR = 0.16  --0.1
NDefines.NDiplomacy.WAR_REPARATIONS_YEARS = 6   --10
NDefines.NDiplomacy.AE_PROVINCE_CAP = 60  --30
NDefines.NDiplomacy.MAX_PEACE_TREATY_AE = 200  --50

--peace cost
NDefines.NDiplomacy.PEACE_COST_DEMAND_PROVINCE = 0.8   --0.8
NDefines.NDiplomacy.PEACE_COST_CONVERSION = 0.4 --0.8
NDefines.NDiplomacy.PEACE_COST_CONCEDE_PROVINCE = 0.8   --0.8
NDefines.NDiplomacy.PEACE_COST_BECOME_VASSAL = 0.6    --0.8
NDefines.NDiplomacy.PEACE_COST_RETURN_CORE = 0.5    --0.8
NDefines.NDiplomacy.PEACE_COST_RELEASE_ANNEXED = 0.6   --0.8
NDefines.NDiplomacy.PEACE_COST_RELEASE_VASSAL = 0.2 --0.4
NDefines.NDiplomacy.PEACE_COST_DEMAND_NON_OCCUPIED_PROVINCE_MULT = 2.5  --1.1
NDefines.NDiplomacy.AUTONOMY_WARSCORE_COST_MODIFIER = 0.5 --0.33
-- NDefines.NDiplomacy.CLAIM_PEACE_COST_DIP_FRACTION = -0.1 -- -0.1
-- NDefines.NDiplomacy.CORE_PEACE_COST_DIP_FRACTION = -0.2 -- -0.1
NDefines.NDiplomacy.ALLY_PEACE_COST_MULT = 5 --2

--天命
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_STATE_WITH_PROSPERITY = 0.04 --0.04
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_TRIBUTARY_DEV = 0.18  --0.15
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_DEVASTATION = -5   -- -10
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_5_LOANS = -0.3 -- -0.6
NDefines.NDiplomacy.TRIBUTE_MAX_MONARCH_POWER = 15 --12


--xorme more monarch trait
NDefines.NCountry.MAX_EXTRA_PERSONALITIES = 3
NDefines.NCountry.FIRST_EXTRA_PERSONALITY = 0
NDefines.NCountry.YEARS_PER_EXTRA_PERSONALITY = 15

--mana
NDefines.NCountry.MAXIMUM_ADVISOR_SKILL = 5 --10 --5
NDefines.NCountry.POWER_MAX = 2499 --999
NDefines.NCountry.BASE_POWER_INCREASE = 4 --3
NDefines.NCountry.PS_ADVANCE_TECH = 800 --600
NDefines.NCountry.TECH_AHEAD_OF_TIME = 0.05 --0.1
NDefines.NCountry.TECH_TIME_COST = 1   --0.3
NDefines.NCountry.EXPLOIT_COOLDOWN_MONTHS = 6  --240
NDefines.NCountry.EXPLOIT_ADM_INCOME = 0
NDefines.NCountry.EXPLOIT_DIP_SAILORS = 0
NDefines.NCountry.EXPLOIT_MIL_MANPOWER = 0

NDefines.NCountry.CORE_LOSE_CULTURE_GROUP = 800    --150
NDefines.NCountry.OVEREXTENSION_FACTOR = 0.4    --0.8
NDefines.NCountry.OVEREXTENSION_OVERSEAS_FACTOR = 0.25  --0.5
NDefines.NCountry.MONTHS_TO_CORE = 48  --36

NDefines.NCountry.HORDE_UNITY_PER_LOOT = 0.1  --0.25
NDefines.NCountry.HORDE_UNITY_PER_RAZE = 0.25  --0.5

NDefines.NCountry.HORDE_RAZE_TECH_BASE_LEVEL = 10   --3
NDefines.NCountry.RAZE_PROVINCE_COOLDOWN_YRS = 0  --20
NDefines.NCountry.COUNTRY_DEVELOPMENT_SCALE = 5000  --600
NDefines.NCountry.OVERSEAS_CLIENT_STATES = 1  --0
NDefines.NCountry.MAXIMUM_CONDOTTIERI = 30  --20

NDefines.NCountry.MIN_LIBERTY_DESIRE_INFLUENCE = -75  -- -100
NDefines.NCountry.LIBERTY_DESIRE_TRUST = -0.6  -- -0.4
NDefines.NCountry.LIBERTY_DESIRE_RELATIVE_POWER = 100  --75
NDefines.NCountry.ENFORCE_CULTURE_TAX_MULTIPLIER = 0 --2

--finance
NDefines.NCountry.STATE_MAINTENANCE_CONTINENT_FACTOR = 0.1 --0.25
NDefines.NCountry.STATE_MAINTENANCE_CULTURE_FACTOR = 0.25   --0.25
NDefines.NCountry.STATE_MAINTENANCE_DEV_FACTOR = 0.007  --0.007
NDefines.NCountry.STATE_MAINTENANCE_DISTANCE_FACTOR = 0.0015  --0.001
NDefines.NCountry.CORRUPTION_COST = 0.1 --0.05

--institution
NDefines.NCountry.EMBRACE_INSTITUTION_COST = 10  --2.5
NDefines.NCountry.INSTITUTION_BONUS_FROM_IMP_DEVELOPMENT = 3.5  --5
NDefines.NCountry.INSTITUTION_CAP_IMP_DEVELOPMENT = 6  --10
NDefines.NCountry.INSTITUTION_BASE_IMP_DEVELOPMENT = 24 --30

NDefines.NCountry.REVOLT_TECH_IMPACT = 0.05  --0.03
NDefines.NCountry.REVOLT_TECH_MORALE = 0.015  --0.1
NDefines.NCountry.REVOLT_SIZE_DEVELOPMENT_MULTIPLIER = 0.15  --0.1

NDefines.NCountry.CULTURAL_UNION_MIN_RANK = 3 -- 3
NDefines.NCountry.CULTURAL_UNION_MIN_DEV = 999999 --1000


NDefines.NEconomy.ADVISOR_COST = 0.75 --1.0
NDefines.NEconomy.EDICTS_COST_INCREASE = 0.25  --2
NDefines.NEconomy.AUTONOMY_AT_CONQUEST_CORE = 20 --0
NDefines.NEconomy.COLONY_MIN_AUTONOMY = 0 --50
NDefines.NEconomy.DECREASE_AUTONOMY_STEP = 0 --25
NDefines.NEconomy.INCREASE_AUTONOMY_STEP = 0 --25

NDefines.NEconomy.LAND_TECH_MAINTENANCE_IMPACT = 0.04 --0.02
NDefines.NEconomy.NAVAL_TECH_MAINTENANCE_IMPACT = 0.03 -- 0.02
NDefines.NEconomy.LAND_TECH_MERC_MAINTENANCE_IMPACT = 0.12 --0.08
NDefines.NEconomy.CAPITAL_MAX_AUTONOMY = 75  --0

NDefines.NEconomy.BANKRUPTCY_PROVINCE_DEVASTATION_GAIN = 5 --10


NDefines.NMilitary.DEFAULT_WARGOAL_BATTLESCORE_BONUS = 8 --3
NDefines.NMilitary.ASSAULT_WIDTH_LIMIT = 10 --5
NDefines.NMilitary.MORALE_RECOVERY_SPEED = 0.12  --0.15
NDefines.NMilitary.MORALE_RECOVERY_SPEED_OWN_TERRITORY = 0.1 --0.05
NDefines.NMilitary.HOSTILE_TERRITORY_SPEED_MODIFIER = 0 -- -0.15  -- 0
NDefines.NMilitary.BASE_MP_TO_MANPOWER = 0.35 --0.25
NDefines.NMilitary.CONTROL_DEVASTATION_IMPACT = -2  -- -1
NDefines.NMilitary.FORT_DEVASTATION_IMPACT = -7.2 -- -10
NDefines.NMilitary.FORTRESS_COST = 0.3 --0.5
NDefines.NMilitary.MONTHLY_REINFORCE = 0.05  --0.1
NDefines.NMilitary.EXTRA_LAND_REINFORCE_COST = 0.75  --2

NDefines.NMilitary.LOOTED_SCALE = 3  --1
NDefines.NMilitary.LOOT_DEVASTATION_IMPACT = 10  --10
NDefines.NMilitary.LOOTED_MAX = 30 --5
NDefines.NMilitary.INF_LOOT = 0.4  --0.1
NDefines.NMilitary.CAV_LOOT = 1  --0.3
NDefines.NMilitary.ART_LOOT = 0.2  --0.05


NDefines.NAI.DEVELOPMENT_CAP_BASE = 30  --10
NDefines.NAI.DEVELOPMENT_CAP_MULT = 10  --2
--NDefines.NAI.AGGRESSIVENESS = 400  -200
--NDefines.NAI.AGGRESSIVENESS_BONUS_EASY_WAR = 1000  --300
--NDefines.NAI.ARTILLERY_FRACTION = 0.25  --0.35
NDefines.NAI.FORCE_COMPOSITION_CHANGE_TECH_LEVEL = 16  --11
NDefines.NAI.PEACE_COALITION_FACTOR = 5 --30
NDefines.NAI.PEACE_REBELS_FACTOR = 40  --20
NDefines.NAI.DIPLOMATIC_ACTION_OFFER_CONDOTTIERI_ONLY_NEIGHBORS = 0 --1

NDefines.NAI.ADVISOR_BUDGET_FRACTION_MAX = 0.4 --0.35
NDefines.NAI.ADVISOR_BUDGET_FRACTION_MIN = 0.1 --0.15
NDefines.NAI.ADVISOR_BUDGET_FRACTION_MERITOCRACY_MAX = 0.6 --0.5
NDefines.NAI.ADVISOR_BUDGET_FRACTION_MERITOCRACY_MIN = 0.25 --0.25
NDefines.NAI.FIRE_ADVISOR_LOAN_REQUIREMENT = 5   --5
NDefines.NAI.DIPLOMATIC_ACTION_OFFER_CONDOTTIERI_BASE_MULT = 50 --33
NDefines.NAI.ADVISOR_PROMOTION_AGE_CUTOFF = 50  --40
NDefines.NAI.PROMOTE_ADVISOR_BASE_AI_DESIRE = 30   --10
NDefines.NAI.AI_FORT_PER_DEV_RATIO = 50  --75
NDefines.NAI.FORT_BUDGET_FRACTION = 0.5  --0.3
NDefines.NAI.FORT_CAPITAL_DESIRE = 100


NDefines.NAI.EDICT_VALUE_THRESHOLD = 5
NDefines.NAI.EDICT_VALUE_THRESHOLD_MULTIPLY_DEFICIT = 3
NDefines.NAI.EDICT_VALUE_THRESHOLD_MULTIPLY_LOW_INCOME = 1
--NDefines.NAI.EDICT_VALUE_THRESHOLD = 60 --120
NDefines.NAI.STATE_MAINTENANCE_BUDGET_FRACTION = 0.8
NDefines.NAI.NOMINAL_ARMY_SIZE_MULTIPLIER = 1.25
NDefines.NAI.MAX_BUILDING_COST_INCOME_MONTHS = 30
NDefines.NAI.MAX_SAVINGS = 40
NDefines.NAI.DESIRED_DEFICIT = 0.2
NDefines.NAI.DESIRED_SURPLUS = 0.3
NDefines.NAI.ONLY_INFANTRY_MERCS = 0
NDefines.NAI.PEACE_TERMS_RETURN_CORES_VASSAL_MULT = 5  --2
NDefines.NAI.PEACE_TERMS_REVOKE_CORES_BASE_MULT = 0 --1
NDefines.NAI.PEACE_TERMS_RELEASE_VASSAL_SAME_CULTURE_MULT = 0.35  --0.65
NDefines.NAI.PEACE_TERMS_RELEASE_VASSAL_SAME_CULTURE_GROUP_MULT = 0.5  --0.75
NDefines.NAI.PEACE_TERMS_RELEASE_ANNEXED_MAX_MULT = 0.6  --1.3
NDefines.NAI.PEACE_TERMS_RELEASE_ANNEXED_SAME_CULTURE_MULT = 0.1  --0.65
NDefines.NAI.PEACE_TERMS_RELEASE_ANNEXED_SAME_CULTURE_GROUP_MULT = 0.2   --0.75
NDefines.NAI.PEACE_TERMS_RELEASE_ANNEXED_HRE_MULT = 10  --2
NDefines.NAI.PEACE_TERMS_WAR_REPARATIONS_BASE_MULT = 2  --0.1
NDefines.NAI.PEACE_TERMS_WAR_REPARATIONS_MIN_INCOME_RATIO = 0.01  --0.5
NDefines.NAI.GOVERNING_CAPACITY_OVER_PERCENTAGE_TOLERATED = 1  --0.5
NDefines.NAI.PEACE_TERMS_PROVINCE_CLAIM_MULT = 6  --2
NDefines.NAI.PEACE_TERMS_PROVINCE_CORE_MULT = 10  --3

NDefines.NAI.PEACE_TERMS_RELEASE_ANNEXED_BASE_MULT = 0.75  --0.75
NDefines.NAI.PEACE_TERMS_RELEASE_ANNEXED_MAX_MULT = 2 --1.3


NDefines.NAIEconomy.STATE_MAINTENANCE_FRACTION = 0.8
NDefines.NAIEconomy.BUDGETING_ADJUSTMENT_STEP = 0.11
NDefines.NAIEconomy.MILITARY_FOCUS_DEFAULT = 2.0
NDefines.NAIEconomy.MILITARY_FOCUS_LOWER_BOUND = 2.0
NDefines.NAIEconomy.MILITARY_FOCUS_UPPER_BOUND = 3.5

NDefines.NAIEconomy.LOAN_REPAYMENT_SAVINGS_PRIORITY = 1000
NDefines.NAIEconomy.LOAN_REPAYMENT_SAVINGS_PRIORITY_WARTIME = 0
--NDefines.NAIEconomy.ARMY_FRACTION_PEACEFUL = 1.5  --2.1
--NDefines.NAIEconomy.ARMY_FRACTION_MILITARIST = 1.7  --2.5
--NDefines.NAIEconomy.ARMY_FRACTION_MILITARIZE = 2.2


NDefines.NNationDesigner.POINTS_AVAILABLE = 800







